version: "3.6"
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
    container_name: wordpress
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress:/var/www/html
      - ../../themes/${WORDPRESS_THEME}/build:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt
      - ../../themes/${WORDPRESS_THEME}/build:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
    depends_on:
      - wordpress
    restart: always

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8080:8080

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USER:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_PORT_3306_TCP_ADDR: mysql

  wp-cli:
    image: "wordpress:cli-${WP_CLI_VERSION:-2.2.0}-php${PHP_VERSION:-7.3}"
    depends_on:
      - "mysql"
    volumes:
      - "./wordpress:/var/www/html:rw"
      #- "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
      #- "../theme:/var/www/html/wp-content/themes/vertical-raise-theme-buildout:ro"

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
